### ISSUE TITLE
Email automation - Email - Business submits form to be notified when a nano-influencer is found. Email sent to biz owner

### ISSUE THREAD

**Issue by maxzad** [lettucesocial/com-lettucesocial-customer-api#7]
When a business user successfully fills out the form to be notified after zero creators are found in a searched zip code, an email will be sent. **Email should go out from hello@lettucesocial.com email address. to business owner's email** 
and **BCC** a copy to mxzadeh@gmail.com

**Subject: Welcome to the LettuceSocial Community!**

Hi {name},
Welcome to the LettuceSocial community!
We appreciate your interest in working with our creators!
We have received your information and will contact you as soon as we find a nano-influencer match in your zip code.
While we're searching for your ideal nano-influencer, why not explore neighboring zip codes? You might just find your perfect match there. 

https://business.lettucesocial.com/creator

And remember, you're part of the LettuceSocial family now- join us on Instagram for more tips and insights on leveraging social media for your business. Give us a follow > [here](https://www.instagram.com/lettucesocial/)

We look forward to working with you soon!

Best regards,
LettuceSocial Team

**Comment by maxzad** [comment]
for your reference, this email goes out after the user lands on this page after filling out the form to be notified.

<img width="225" alt="Screenshot 2023-12-17 at 12 34 18 PM" src="https://github.com/lettucesocial/com-lettucesocial-customer-panel/assets/19561243/72ec437a-a078-4f86-b7f2-f3ee5e3448ad">

**Comment by maxzad** [comment]
please note that i used https in the URL in the body of email and it is dependent on completing lettucesocial/com-lettucesocial-customer-panel#34

**Comment by mohsenxad** [comment]
email template name : welcome-email-to-business

**Comment by mohsenxad** [comment]
@maxzad 

require to do lettucesocial/com-lettucesocial-customer-panel#51

**Comment by maxzad** [comment]
tested -
