### ISSUE TITLE
Email automation - Email - After a successful deposit payment hold is processed - Biz owner gets

### ISSUE THREAD

**Issue by maxzad** [lettucesocial/com-lettucesocial-customer-api#8]
**Email should go out from [hello@lettucesocial.com](mailto:hello@lettucesocial.com) email address. to Business Owner email**
and **BCC** a copy to mxzadeh@gmail.com

Please note the bullet point indentation

**Subject: LettuceSocial - We Received Your Collaboration Request**

Hi {name},

We are super excited about our collaboration and looking forward to helping you grow {business name} through local social media advocacy by LettuceSocial nano-influencers.

Below is what comes next to kick off {business name}'s collaboration.

- LettuceSocial will notify you (via email and text) within 3 business days if the nano-influencer ({creator Instagram handle}) is willing and able to collaborate with you. The 10% deposit you made will only be charged once the nano-influencer accepts the offer. Until then, it will remain on hold. In case the nano-influencer declines the offer, the hold on your 10% deposit will be released.
- LettuceSocial will build the business page for {business name} on the LettuceSocial website (LettuceSocial will reach out with the information needed to finalize the business page).
- Agree on what free offering {business name} can provide to the nano-influencer. This is important for two reasons:
    - The nano-influencer will be able to meet with you/your general manager to learn about your story as a local business owner, your services, and what aspects of the business/services need to be highlighted.
    - The nano-influencer gets to experience your product/services and create authentic content.
- LettuceSocial will connect you with your nano-influencer to coordinate the first visit.

Please feel free to reach out to us with any questions.

Looking forward to working with you on this exciting collaboration.

Best regards,
LettuceSocial Team
[Follow us on Instagram](https://www.instagram.com/lettucesocial/)

**Comment by mohsenxad** [comment]
first create a template email in mailgun for this email

**Comment by maxzad** [comment]
@mohsenxad 

are you asking me to create an email template or you doing it?

if you want me to do it, do you need me to do HTML or Visual Builder?

**Comment by maxzad** [comment]
tested - done
